version: "3"
services:
   mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
      restart: always
      environment:
          MYSQL_DATABASE: book
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          HOST: mysql
      volumes:
         - ./flight_booking.sql:/docker-entrypoint-initdb.d/flight_booking.sql
      #ports:
      #  - 3336:3306
   challenge:
     build: .
     restart: always
     ports:
      - "8080:80"
     depends_on:
       - mysql