[project]
name = "dream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.12.15",
    "extendedrandcrack>=1.0.0",
    "pwntools>=4.14.1",
    "randcrack>=0.2.0",
    "scipy>=1.13.1",
    "soundfile>=0.13.1",
    "tqdm>=4.67.1",
]
