version: "3.8"
services:
  app:
    build: ./app
    environment:
      FLAG: hkcert23{dummy}
    ports:
      - "28107:5000"
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: s2rYMCv3g2Gk
